# Indicates if the database features are enabled.
enabled: true


# Database command namespace.
# It allows to change default "db:migrate" to "database:migrate", for instance.
command_namespace: '{{DB_COMMAND_NAMESPACE|db}}'


# Default connection to use
default: '{{DB_CONNECTION|sqlite}}'


# All available static connections.
connections:

  sqlite:
    driver: sqlite
    filename: '{{DB_FILE|@/storage/databases/database.sqlite}}'

  mysql:
    driver: mysql
    host: '{{DB_HOST}}'
    user: '{{DB_USER}}'
    password: '{{DB_PASSWORD}}'
    database: '{{DB_NAME}}'
    port: '{{DB_PORT|3306}}'


# Paths to the different database-related folders from the database folder.
# This will be used when creating the Knex instance.
paths:
  factories: 'factories'
  migrations: 'migrations'
  models: 'models'
  seeds: 'seeds'


# The migrations table to be used by Knex.
# It's set to "migrations" by default, but feel freee to change it.
migration_table: 'migrations'
